# Generated by Django 4.2 on 2023-05-06 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=10)),
                ("cep", models.CharField(max_length=9)),
                (
                    "complement",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
