# Generated by Django 4.2 on 2023-05-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
        ("carts", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartlistproducts",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_list",
                to="carts.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartlistproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_list",
                to="products.product",
            ),
        ),
    ]
