# Generated by Django 4.2 on 2023-05-02 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default=None, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_stock", models.IntegerField()),
                ("is_available_for_sale", models.BooleanField(default=False)),
                ("brand", models.CharField(max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Eletronics", "Eletronics"),
                            ("Clothing", "Clothing"),
                            ("Shoes", "Shoes"),
                            ("Toys", "Toys"),
                            ("Sports", "Sports"),
                            ("Health", "Health"),
                            ("School", "School"),
                            ("Books", "Books"),
                            ("Crafts", "Crafts"),
                            ("Home", "Home"),
                            ("Beauty", "Beauty"),
                            ("Garden", "Garden"),
                            ("Grocery", "Grocery"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
